FROM node:16.16.0-alpine

WORKDIR /app

RUN apk update && apk upgrade && apk --no-cache --virtual build-dependencies add \
    python3 \
    make \
    g++

COPY . .

EXPOSE 3031

ENTRYPOINT ["sh", "/app/entrypoint.sh"]